# Specification v5.4  Vol 4 Part E

from enum import IntEnum
from enum import Enum
from enum import unique

class Address(IntEnum):
    PUBLIC = 0x00
    RANDOM = 0x01
    RESOLVABLE_PUBLIC = 0x02
    RESOLVABLE_RANDOM = 0x03
    ANONYMOUS = 0xFF

class Advertising(IntEnum):
    DISABLED = 0x00
    ENABLED = 0x01

class AdvertisingChannelMap(IntEnum):
    CHANNEL_37 = 0x01
    CHANNEL_38 = 0x02
    CHANNEL_39 = 0x04
    ALL_CHANNELS = 0x07

class AdvertisingDataType(IntEnum):
    FLAGS = 0x01
    INCOMPLETE_LIST_16BIT_UUIDS = 0x02
    COMPLETE_LIST_16BIT_UUIDS = 0x03
    INCOMPLETE_LIST_32BIT_UUIDS = 0x04
    COMPLETE_LIST_32BIT_UUIDS = 0x05
    INCOMPLETE_LIST_128BIT_UUIDS = 0x06
    COMPLETE_LIST_128BIT_UUIDS = 0x07
    SHORTENED_LOCAL_NAME = 0x08
    COMPLETE_LOCAL_NAME = 0x09
    TX_POWER_LEVEL = 0x0A
    MANUFACTURER_SPECIFIC_DATA = 0xFF

class AdvertisingFilterPolicy(IntEnum):
    SCAN_CONNECT_ALL = 0x00
    SCAN_FILTER_CONNECT_ALL = 0x01
    SCAN_ALL_CONNECT_FILTER = 0x02
    SCAN_CONNECT_FILTER_ONLY = 0x03

class AdvertisingType(IntEnum):
    ADV_IND = 0x00
    ADV_DIRECT_IND_HIGH = 0x01
    ADV_SCAN_IND = 0x02
    ADV_NONCONN_IND = 0x03
    ADV_DIRECT_IND_LOW = 0x04

class ATTChannelID(IntEnum):
    BLE = 0x0004

@unique
class ATTErrorCode(IntEnum):
    SUCCESS = 0x00
    INVALID_HANDLE = 0x01  # The attribute handle given was not valid on this server.
    READ_NOT_PERMITTED = 0x02  # The attribute cannot be read.
    WRITE_NOT_PERMITTED = 0x03  # The attribute cannot be written.
    INVALID_PDU = 0x04  # The attribute PDU was invalid.
    INSUFFICIENT_AUTHENTICATION = 0x05  # The attribute requires authentication before it can be read or written.
    REQUEST_NOT_SUPPORTED = 0x06  # ATT Server does not support the request received from the client.
    INVALID_OFFSET = 0x07  # Offset specified was past the end of the attribute.
    INSUFFICIENT_AUTHORIZATION = 0x08  # The attribute requires authorization before it can be read or written.
    PREPARE_QUEUE_FULL = 0x09  # Too many prepare writes have been queued.
    ATTRIBUTE_NOT_FOUND = 0x0A  # No attribute found within the given attribute handle range.
    ATTRIBUTE_NOT_LONG = 0x0B  # The attribute cannot be read using the ATT_READ_BLOB_REQ PDU.
    ENCRYPTION_KEY_SIZE_TOO_SHORT = 0x0C  # The Encryption Key Size used for encrypting this link is too short.
    INVALID_ATTRIBUTE_VALUE_LENGTH = 0x0D  # The attribute value length is invalid for the operation.
    UNLIKELY_ERROR = 0x0E  # The request encountered an unlikely error.
    INSUFFICIENT_ENCRYPTION = 0x0F  # The attribute requires encryption before it can be read or written.
    UNSUPPORTED_GROUP_TYPE = 0x10  # The attribute type is not a supported grouping attribute.
    INSUFFICIENT_RESOURCES = 0x11  # Insufficient resources to complete the request.
    DATABASE_OUT_OF_SYNC = 0x12  # The server requests the client to rediscover the database.
    VALUE_NOT_ALLOWED = 0x13  # The attribute parameter value was not allowed.
    APPLICATION_ERROR_START = 0x80  # Application-specific error codes start here (0x80 to 0x9F).
    APPLICATION_ERROR_END = 0x9F
    COMMON_PROFILE_SERVICE_ERROR_START = 0xE0  # Common profile and service error codes start here (0xE0 to 0xFF).
    COMMON_PROFILE_SERVICE_ERROR_END = 0xFF

@unique
class BLEErrorCode(IntEnum):
    SUCCESS = 0x00
    UNKNOWN_HCI_COMMAND = 0x01
    UNKNOWN_CONNECTION_IDENTIFIER = 0x02
    HARDWARE_FAILURE = 0x03
    PAGE_TIMEOUT = 0x04
    AUTHENTICATION_FAILURE = 0x05
    PIN_OR_KEY_MISSING = 0x06
    MEMORY_CAPACITY_EXCEEDED = 0x07
    CONNECTION_TIMEOUT = 0x08
    CONNECTION_LIMIT_EXCEEDED = 0x09
    SYNC_CONN_LIMIT_TO_DEVICE_EXCEEDED = 0x0A
    CONNECTION_ALREADY_EXISTS = 0x0B
    COMMAND_DISALLOWED = 0x0C
    CONNECTION_REJECTED_DUE_TO_LIMITED_RESOURCES = 0x0D
    CONNECTION_REJECTED_DUE_TO_SECURITY = 0x0E
    CONNECTION_REJECTED_DUE_TO_UNACCEPTABLE_BD_ADDR = 0x0F
    CONNECTION_ACCEPT_TIMEOUT_EXCEEDED = 0x10
    UNSUPPORTED_FEATURE_OR_PARAMETER_VALUE = 0x11
    INVALID_HCI_COMMAND_PARAMETERS = 0x12
    REMOTE_USER_TERMINATED_CONNECTION = 0x13
    REMOTE_DEVICE_TERMINATED_LOW_RESOURCES = 0x14
    REMOTE_DEVICE_TERMINATED_POWER_OFF = 0x15
    CONNECTION_TERMINATED_BY_LOCAL_HOST = 0x16
    REPEATED_ATTEMPTS = 0x17
    PAIRING_NOT_ALLOWED = 0x18
    UNKNOWN_LMP_PDU = 0x19
    UNSUPPORTED_REMOTE_FEATURE = 0x1A
    SCO_OFFSET_REJECTED = 0x1B
    SCO_INTERVAL_REJECTED = 0x1C
    SCO_AIR_MODE_REJECTED = 0x1D
    INVALID_LMP_PARAMETERS = 0x1E
    UNSPECIFIED_ERROR = 0x1F
    UNSUPPORTED_LMP_PARAMETER_VALUE = 0x20
    ROLE_CHANGE_NOT_ALLOWED = 0x21
    LMP_RESPONSE_TIMEOUT = 0x22
    LMP_ERROR_TRANSACTION_COLLISION = 0x23
    LMP_PDU_NOT_ALLOWED = 0x24
    ENCRYPTION_MODE_NOT_ACCEPTABLE = 0x25
    LINK_KEY_CANNOT_BE_CHANGED = 0x26
    REQUESTED_QOS_NOT_SUPPORTED = 0x27
    INSTANT_PASSED = 0x28
    PAIRING_WITH_UNIT_KEY_NOT_SUPPORTED = 0x29
    DIFFERENT_TRANSACTION_COLLISION = 0x2A
    RESERVED_FOR_FUTURE_USE_2B = 0x2B
    QOS_UNACCEPTABLE_PARAMETER = 0x2C
    QOS_REJECTED = 0x2D
    CHANNEL_CLASSIFICATION_NOT_SUPPORTED = 0x2E
    INSUFFICIENT_SECURITY = 0x2F
    PARAMETER_OUT_OF_MANDATORY_RANGE = 0x30
    RESERVED_FOR_FUTURE_USE_31 = 0x31
    ROLE_SWITCH_PENDING = 0x32
    RESERVED_FOR_FUTURE_USE_33 = 0x33
    RESERVED_SLOT_VIOLATION = 0x34
    ROLE_SWITCH_FAILED = 0x35
    EXTENDED_INQUIRY_RESPONSE_TOO_LARGE = 0x36
    SSP_NOT_SUPPORTED_BY_HOST = 0x37
    HOST_BUSY_PAIRING = 0x38
    CONNECTION_REJECTED_NO_SUITABLE_CHANNEL = 0x39
    CONTROLLER_BUSY = 0x3A
    UNACCEPTABLE_CONNECTION_PARAMETERS = 0x3B
    ADVERTISING_TIMEOUT = 0x3C
    CONNECTION_TERMINATED_DUE_TO_MIC_FAILURE = 0x3D
    CONNECTION_FAILED_TO_BE_ESTABLISHED = 0x3E
    PREVIOUSLY_USED = 0x3F
    COARSE_CLOCK_ADJUSTMENT_REJECTED = 0x40
    TYPE0_SUBMAP_NOT_DEFINED = 0x41
    UNKNOWN_ADVERTISING_IDENTIFIER = 0x42
    LIMIT_REACHED = 0x43
    OPERATION_CANCELLED_BY_HOST = 0x44
    PACKET_TOO_LONG = 0x45
    TOO_LATE = 0x46
    TOO_EARLY = 0x47

class BroadcastFlags(IntEnum):
    POINT_POINT = 0b00
    ACTIVE = 0b01
    PARKED = 0b10

@unique
class EventMask(IntEnum):
    INQUIRY_COMPLETE = 0
    INQUIRY_RESULT = 1
    CONNECTION_COMPLETE = 2
    CONNECTION_REQUEST = 3
    DISCONNECTION_COMPLETE = 4
    AUTHENTICATION_COMPLETE = 5
    REMOTE_NAME_REQUEST_COMPLETE = 6
    ENCRYPTION_CHANGE = 7
    CHANGE_CONNECTION_LINK_KEY_COMPLETE = 8
    LINK_KEY_TYPE_CHANGED = 9
    READ_REMOTE_SUPPORTED_FEATURES_COMPLETE = 10
    READ_REMOTE_VERSION_INFO_COMPLETE = 11
    QOS_SETUP_COMPLETE = 12
    HARDWARE_ERROR = 15
    FLUSH_OCCURRED = 16
    ROLE_CHANGE = 17
    MODE_CHANGE = 19
    RETURN_LINK_KEYS = 20
    PIN_CODE_REQUEST = 21
    LINK_KEY_REQUEST = 22
    LINK_KEY_NOTIFICATION = 23
    LOOPBACK_COMMAND = 24
    DATA_BUFFER_OVERFLOW = 25
    MAX_SLOTS_CHANGE = 26
    READ_CLOCK_OFFSET_COMPLETE = 27
    CONNECTION_PACKET_TYPE_CHANGED = 28
    QOS_VIOLATION = 29
    PREVIOUSLY_USED = 30
    PAGE_SCAN_REPETITION_MODE_CHANGE = 31
    FLOW_SPECIFICATION_COMPLETE = 32
    INQUIRY_RESULT_WITH_RSSI = 33
    READ_REMOTE_EXTENDED_FEATURES_COMPLETE = 34
    SYNCHRONOUS_CONNECTION_COMPLETE = 43
    SYNCHRONOUS_CONNECTION_CHANGED = 44
    SNIFF_SUBRATING = 45
    EXTENDED_INQUIRY_RESULT = 46
    ENCRYPTION_KEY_REFRESH_COMPLETE = 47
    IO_CAPABILITY_REQUEST = 48
    IO_CAPABILITY_RESPONSE = 49
    USER_CONFIRMATION_REQUEST = 50
    USER_PASSKEY_REQUEST = 51
    REMOTE_OOB_DATA_REQUEST = 52
    SIMPLE_PAIRING_COMPLETE = 53
    LINK_SUPERVISION_TIMEOUT_CHANGED = 55
    ENHANCED_FLUSH_COMPLETE = 56
    USER_PASSKEY_NOTIFICATION = 58
    KEYPRESS_NOTIFICATION = 59
    REMOTE_HOST_SUPPORTED_FEATURES_NOTIFICATION = 60
    LE_META_EVENT = 61

@unique
class EventType(IntEnum):
    CONNECTION_COMPLETE = 0
    ADVERTISING_REPORT = 1
    CONNECTION_UPDATE_COMPLETE = 2
    READ_REMOTE_FEATURES_COMPLETE = 3
    LONG_TERM_KEY_REQUEST = 4
    REMOTE_CONNECTION_PARAMETER_REQUEST = 5
    DATA_LENGTH_CHANGE = 6
    READ_LOCAL_P256_PUBLIC_KEY_COMPLETE = 7
    GENERATE_DHKEY_COMPLETE = 8
    ENHANCED_CONNECTION_COMPLETE_V1 = 9
    DIRECTED_ADVERTISING_REPORT = 10
    PHY_UPDATE_COMPLETE = 11
    EXTENDED_ADVERTISING_REPORT = 12
    PERIODIC_ADV_SYNC_ESTABLISHED_V1 = 13
    PERIODIC_ADV_REPORT_V1 = 14
    PERIODIC_ADV_SYNC_LOST = 15
    SCAN_TIMEOUT = 16
    ADV_SET_TERMINATED = 17
    SCAN_REQUEST_RECEIVED = 18
    CHANNEL_SELECTION_ALGORITHM = 19
    CONNECTIONLESS_IQ_REPORT = 20
    CONNECTION_IQ_REPORT = 21
    CTE_REQUEST_FAILED = 22
    PERIODIC_ADV_SYNC_TRANSFER_RECEIVED_V1 = 23
    CIS_ESTABLISHED = 24
    CIS_REQUEST = 25
    CREATE_BIG_COMPLETE = 26
    TERMINATE_BIG_COMPLETE = 27
    BIG_SYNC_ESTABLISHED = 28
    BIG_SYNC_LOST = 29
    REQUEST_PEER_SCA_COMPLETE = 30
    PATH_LOSS_THRESHOLD = 31
    TRANSMIT_POWER_REPORTING = 32
    BIGINFO_ADV_REPORT = 33
    SUBRATE_CHANGE = 34
    PERIODIC_ADV_SYNC_ESTABLISHED_V2 = 35
    PERIODIC_ADV_REPORT_V2 = 36
    PERIODIC_ADV_SYNC_TRANSFER_RECEIVED_V2 = 37
    PERIODIC_ADV_SUBEVENT_DATA_REQUEST = 38
    PERIODIC_ADV_RESPONSE_REPORT = 39
    ENHANCED_CONNECTION_COMPLETE_V2 = 40

class GATTAttributes(Enum):
    PRIMARY_SERVICE = "2800"
    SECONDARY_SERVICE = "2801"
    INCLUDE = "2802"
    CHARACTERISTIC = "2803"
    CHARACTERISTIC_EXT_PROPERTIES = "2900"
    CHARACTERISTIC_USER_DESC = "2901"
    CLIENT_CHAR_CONFIG = "2902"
    SERVER_CHAR_CONFIG = "2903"
    CHARACTERISTIC_PRESENTATION_FORMAT = "2904"
    CHARACTERISTIC_AGGREGATE_FORMAT = "2905"

# Not Complete list of HCI Events,
# see Specification v5.4 Vol 4 Part E 7.7
@unique
class HCIEvents(IntEnum):
    DISCONNECTION_COMPLETE = 0x05
    COMMAND_COMPLETE = 0x0E
    COMMAND_STATUS = 0x0F
    COMPLETED_PACKETS = 0x13
    META_EVENT = 0x3E
    VENDOR_SPECIFIC = 0xFF

@unique
class HCIPacket(IntEnum):
    ACK = 0x00
    COMMAND = 0x01
    ACL_DATA = 0x02
    SYNC_DATA = 0x03
    EVENT = 0x04
    ISO_DATA = 0x05
    VENDOR_SPECIFIC = 0x14
    LINK_CONTROL = 0x15

class InitiatorFilter(IntEnum):
    FILTER_ACCEPT_NOT_USED = 0x00
    FILTER_ACCEPT_USED = 0x01

class PacketBoundaryFlags(IntEnum):
    CONTINUING_FRAGMENT = 0b00
    FIRST_FRAGMENT = 0b01
    COMPLETE_MESSAGE = 0b10

class PeerAddress(IntEnum):
    PUBLIC_DEVICE = 0x00
    RANDOM_DEVICE = 0x01

class ScanEnable(IntEnum):
    ALL_DISABLED = 0x00
    INQUIRY_ENABLED_PAGE_DISABLED = 0x01
    INQUIRY_DISABLED_PAGE_ENABLED = 0x02
    ALL_ENABLED = 0x03

class ScanningFilter(IntEnum):
    BASIC_UNFILTERED = 0x00
    BASIC_FILTERED = 0x01
    EXTENDED_UNFILTERED = 0x02
    EXTENDED_FILTERED = 0x03

class ScanningFilterDuplicate(IntEnum):
    DISABLED = 0x00
    ENABLED = 0x01

class ScanningStatus(IntEnum):
    DISABLED = 0x00
    ENABLED = 0x01

class ScanningType(IntEnum):
    PASSIVE = 0x00
    ACTIVE = 0x01

